# roles/ipv6_dns_sync/handlers/main.yml
#
# Handlers are triggered by 'notify' in tasks and run once at the end
# of the play, even if notified multiple times.

---

- name: Reload systemd
  systemd:
    daemon_reload: true

- name: Reload launchd plist
  command: >
    launchctl unload /Library/LaunchDaemons/au.hosteng.ipv6-dns-watch.plist &&
    launchctl load -w /Library/LaunchDaemons/au.hosteng.ipv6-dns-watch.plist
  ignore_errors: true
